package com.app.usermanagement.util;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;


// I tried the user id to be autogenerated, but it is not fully completed in time
@Document(collection = "database_sequences")
public class DatabaseSequence {

    @Id
    private String id;

    private long seq;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getSeq() {
        return seq;
    }

    public void setSeq(long seq) {
        this.seq = seq;
    }
}

